apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: jellyfin
  name: test-pod
  namespace: jellyfin
spec:
  containers:
  - image: nginx
    name: test-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
