apiVersion: v1
kind: Service
metadata:
  name: prowlarr-service
  namespace: jellyfin
spec:
  selector:
    app: prowlarr
  type: NodePort
  ports:
    - port: 9696
      targetPort: 9696
      nodePort: 30050
