apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config-pvc
  namespace: jellyfin
spec:
  storageClassName: jellyfin-storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
