apiVersion: v1
kind: Service
metadata:
  name: jellyfin-service
  namespace: jellyfin
spec:
  selector:
    app: jellyfin
  type: NodePort
  ports:
    - port: 8096
      targetPort: 8096
      nodePort: 30000
