apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-tvseries-pvc
  namespace: jellyfin
spec:
  storageClassName: jellyfin-storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
